### ISSUE TITLE
How to deal with Controller As syntax

### ISSUE THREAD

**Issue by lucasmreis** [christianalfoni/baobab-angular#2]
`$scope.$listenTo` also stop the `$scope` from listening when destroyed. 

How could that be achieved with the Controller As syntax, in which `$scope` is not used?

**Comment by christianalfoni** [comment]
Hi @lucasmreis ,

You still have access to the $scope when using `controllerAs`, so you would have to use that. This was also a question on flux-angular. Was thinking of creating a "component" concept, but it was voted down :-)

Check the suggestion at the bottom of this issue: https://github.com/christianalfoni/flux-angular/issues/28. 

What are you thoughts on this?

**Comment by lucasmreis** [comment]
Yeah, it seems one cannot escape `$scope` on those cases... That's ok. I don't think we need to create something like `.component` just for this.

**Comment by christianalfoni** [comment]
Cool :-)
